name: webapp

on: [push, pull_request]

jobs:
  webapp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webapp

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
 
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 17.9.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  api.orders:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    defaults:
      run:
        working-directory: ./api.orders
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest tests
