name: webapp

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webapp

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
 
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 17.9.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
